- name: install catalouge component
  hosts: catalouge
  become: yes
  tasks:
  - name: setup npm source
    ansible.builtin.shell: "curl -sL https://rpm.nodesource.com/setup_lts.x | bash"
  - name: install nodejs
    ansible.builtin.yum:
      name: nodejs
      state: installed
  - name: check roboshop user exit or not
    ansible.builtin.command: id roboshop
    register: out
    ignore_errors: true
  - when: out.rc !=0
    ansible.builtin.user:
    name: roboshop
  - name: check /app dirctory exit or not
    ansible.builtin.stat:
      path: /app
      register: directory
  - name: print the dirctory status
    ansible.builtin.debug:
      msg: "output: {{directory}}"
      

    