- name: install mongodb component
  hosts: mongodb
  become: yes
  tasks:
  - name: copy the mongodb repo to yum.repos.d
    ansible.builtin.copy:
      src: mongodb.repo
      dest:/etc/yum.repos.d/mongo.repo
  - name: install mongodb org
    ansible.builtin.yum:
      name: mongodb-org
      state: installed